from sys import argv
script, filename = argv
print("we are going to erase %s" % filename)
print ("If you dont want that hit cntrl c")
print("if you donot want that hit return")
input("?")
print("opening the file")
target = open(filename,'w')
print("truncating the file")
target.truncate()
print("now i am going to ask 3 lines")
line1=input("line 1")
line2=input("line 2")
line3=input("line 3")
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")
target.close()